### ISSUE TITLE
[IDEA] A small suggestion

### ISSUE THREAD

**Issue by The-Nyla** [IWickGames/Minecraft-Server-Finder#1]
I was just wondering if it would be possible to allow the program to, when paused or when finished, generate a text document with a list of all the server addresses, also perhaps with slight more info, like in this format:

----------------------------------------------------
Server Address: [ADDRESS]
motd: [MOTD]
version: [SERVER VERSION (1.12 vanilla, 1.16.3 forge, 1.17.1 purpur, 1.15.2 fabric, 1.8 spigot etc.)]
----------------------------------------------------

I just think this would be a nice useful feature. also, the program is amazing, thank you!

**Comment by iwickdev** [comment]
Thanks for for the idea! I was thinking of doing this as well, will get started on that at some point. Don't know when I will finish but definitely on the ideas list. Will close this issue when its added so you know.

**Comment by The-Nyla** [comment]
Thanks!

Also, one more idea that is related to this would be to also say whether or not the server has a whitelist enabled. Also the abilty to filter the listed servers by server version (forge, fabric, pupur, vanilla, etc.), version (1.7.10, 1.16.5, etc.), and whitelist enabled/disabled. which would be great for excluding modded servers and servers with whitelists.

**Comment by iwickdev** [comment]
> 
> 
> Thanks!
> 
> Also, one more idea that is related to this would be to also say whether or not the server has a whitelist enabled. Also the abilty to filter the listed servers by server version (forge, fabric, pupur, vanilla, etc.), version (1.7.10, 1.16.5, etc.), and whitelist enabled/disabled. which would be great for excluding modded servers and servers with whitelists.

Hmm I am unsure if that is actually possible to tell if the server is whitelisted just from the ping response. I know you can get information such as the version the server is using such as PaperSpigot or Spigot (and its version number) and players online however I don't believe whitelists are a part of that.

**Comment by The-Nyla** [comment]
yeah, I wasn't sure about that either, it would be useful if it is, but otherwise that would require a more complicated program that would hook into a minecraft account and fake a player joining each IP, which wouldn't be very efficient.

**Comment by iwickdev** [comment]
Sorry for the long delay but I have added this feature in. There is now an export button at the bottom of the screen that allows you to export your results to a file with this format;

Server IP Port <> Server Version and protocol name
MOTD (May require more than one line due to servers using multiple lines)

**Comment by The-Nyla** [comment]
Thanks! I can't wait to test it out, this makes listing, organizing, and sharing server IP lists much easier! However the download is flagged as containing a virus so it would be nice if you could look into and possibly fix that
