### ISSUE TITLE
A cool idea I had that would make using the program much easier

### ISSUE THREAD

**Issue by The-Nyla** [IWickGames/Minecraft-Server-Finder#2]
I recently found out that there's a minecraft mod that lets you use python in mods. This could be used to run the program in-game as a fabric mod. Or at least a simple mod that connects to the external program and saves the list of IPs in-game. the list would be accessible from a button in the multiplayer menu, and each IP would be clickable, instantly connecting you to that server. Either one of these would make it much easier to use, as it would eliminate the need to manually type in IP addresses, and running as an in-game program would also be nice, though it might be easier and better to run the main program externally now that I think about it.

**Comment by iwickdev** [comment]
Hmm that would be interesting however this program scans IP regions, large ones at that so it would kinda be a drag to leave Minecraft running for like 2 days while it scans.

Just wanted to clarify how those other ones work so fast such as in the Wurst client is take in a starter IP and then moves the IP range around that to find similar servers. This program scans entire IP ranges searching for anything meaning it scans everything in between not just variations. So that means this program takes exponentially longer than that way.

**Comment by The-Nyla** [comment]
I know, I realized that as I wrote the comment, but I still think a mod that can take a list of IPs in a text file, or directly grabs the IPs from the program, and allows you to click that text to join servers, instead of having to add a server to the server list, or edit one every time, would be incredibly useful. another useful feature would be the ability to add a "note" about those IPs when right-clicking then from in-game. it would show up as a tooltip, and would allow someone to keep track of the IPs they had already joined, so they remember which ones are which.

My idea for how it would look is just a button in the multiplayer menu, that brings up the list, each line counts as a separate IP. left-clicking would join that IP, right-clicking gives you the option to delete, copy, or leave a note, and hovering over an IP shows a note (if there is one), and also pings the server, showing basic info (online/offline, # of players, and motd) at the top of the tooltip

**Comment by The-Nyla** [comment]
as another note, I'm actually interested in learning java and python, as python seems to be pretty useful, and I run a server myself, so if I can figure out java, I might actually try to make a mod that does that myself, might take a while though.

**Comment by The-Nyla** [comment]
Closing this because the export button was added and making a compatible mod would require hosting a database of all the located servers for clients to connect to.
